## Semi - ERD diagram

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [12]:
headerDf = pd.read_csv("BronzeLayerData/2019/header/ams__header_2019__202001080000_part_2.csv")

headerDf

C:\Users\EF782XL\AppData\Local\Temp\ipykernel_6160\4222553437.py:1: DtypeWarning: Columns (0: secondary_notify_party_3, 1: secondary_notify_party_4, 2: secondary_notify_party_5, 3: secondary_notify_party_6) have mixed types. Specify dtype option on import or set low_memory=False.
  headerDf = pd.read_csv("BronzeLayerData/2019/header/ams__header_2019__202001080000_part_2.csv")

,identifier,carrier_code,vessel_country_code,vessel_name,port_of_unlading,estimated_arrival_date,foreign_port_of_lading_qualifier,foreign_port_of_lading,manifest_quantity,manifest_unit,weight,weight_unit,measurement,measurement_unit,record_status_indicator,place_of_receipt,port_of_destination,foreign_port_of_destination_qualifier,foreign_port_of_destination,conveyance_id_qualifier,conveyance_id,in_bond_entry_type,mode_of_transportation,secondary_notify_party_1,secondary_notify_party_2,secondary_notify_party_3,secondary_notify_party_4,secondary_notify_party_5,secondary_notify_party_6,secondary_notify_party_7,secondary_notify_party_8,secondary_notify_party_9,secondary_notify_party_10,actual_arrival_date
0,2019070888900,HLCU,MH,BALTIC NORTH,"Tacoma, Washington",2019-07-07,Schedule K Foreign Port,"Tokyo ,Japan",403,PCS,7925,Kilograms,0,NaN,New,"SENDAI-SHINKO, MI",NaN,NaN,NaN,IMO Number/Lloyds Number,9463310,NaN,"Vessel, containerized",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-07
1,2019070888901,HLCU,MH,BALTIC NORTH,"Tacoma, Washington",2019-07-07,Schedule K Foreign Port,"Tokyo ,Japan",490,PCS,7223,Kilograms,0,NaN,New,"SENDAI-SHINKO, MI",NaN,NaN,NaN,IMO Number/Lloyds Number,9463310,NaN,"Vessel, containerized",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-07
2,2019070888902,HLCU,MH,BALTIC NORTH,"Tacoma, Washington",2019-07-07,Schedule K Foreign Port,"Tokyo ,Japan",51687,PCS,53378,Kilograms,0,NaN,New,"YOKOHAMA, JP",NaN,NaN,NaN,IMO Number/Lloyds Number,9463310,NaN,"Vessel, containerized",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-07
3,2019070888903,HLCU,MH,BALTIC NORTH,"Tacoma, Washington",2019-07-07,Schedule K Foreign Port,"Tokyo ,Japan",4437,PCS,8768,Kilograms,0,NaN,New,"YOKOHAMA, JP",NaN,NaN,NaN,IMO Number/Lloyds Number,9463310,NaN,"Vessel, containerized",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-07
4,2019070888904,MLGD,MH,BALTIC NORTH,"Tacoma, Washington",2019-07-11,Schedule K Foreign Port,"Tokyo ,Japan",99,CTN,1026,Kilograms,0,NaN,New,TOKYO,NaN,NaN,NaN,Conveyance Name,BALTIC NORTH,NaN,"Vessel, containerized",ONEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999995,2019100726816,SVDL,DE,CHICAGO EXPRESS,"Savannah, Georgia",2019-10-05,Schedule K Foreign Port,"La Spezia,Italy",149,CTN,2457,Kilograms,0,Cubic Meters,New,SAN GIOVANNI AL N,NaN,NaN,NaN,Conveyance Name,CHICAGO EXPRESS,NaN,"Vessel, containerized",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-05
4999996,2019100726817,SVDL,DE,CHICAGO EXPRESS,"Savannah, Georgia",2019-10-05,Schedule K Foreign Port,"La Spezia,Italy",192,CTN,2358,Kilograms,0,Cubic Meters,New,SAN GIOVANNI AL N,NaN,NaN,NaN,Conveyance Name,CHICAGO EXPRESS,NaN,"Vessel, containerized",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-05
4999997,2019100726818,SVDL,DE,CHICAGO EXPRESS,"Savannah, Georgia",2019-10-05,Schedule K Foreign Port,"La Spezia,Italy",19,CTN,19580,Kilograms,0,Cubic Meters,New,VIGNOLA,NaN,NaN,NaN,Conveyance Name,CHICAGO EXPRESS,NaN,"Vessel, containerized",HLCU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-05
4999998,2019100726819,GNSI,DE,CHICAGO EXPRESS,"Savannah, Georgia",2019-10-03,Schedule K Foreign Port,"La Spezia,Italy",1050,CTN,22860,Kilograms,0,Cubic Meters,New,PAVULLO,NaN,NaN,NaN,Conveyance Name,CHICAGO EXPRESS,NaN,"Vessel, containerized",ONEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-05
4999999,2019100726820,SVDL,DE,CHICAGO EXPRESS,"Savannah, Georgia",2019-10-05,Schedule K Foreign Port,"La Spezia,Italy",1626,CTN,10891,Kilograms,0,Cubic Meters,New,PARMA,NaN,NaN,NaN,Conveyance Name,CHICAGO EXPRESS,NaN,"Vessel, containerized",YMLU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-05

In [8]:
ams_shipper = pd.read_csv("BronzeLayerData/2019/shipper/ams__shipper_2019__202001080000_part_0.csv")

ams_shipper.isna().sum()

identifier                       0
shipper_party_name               8
shipper_party_address_1         21
shipper_party_address_2    1346184
shipper_party_address_3    3809253
shipper_party_address_4    8924645
city                       7268437
state_province             9140132
zip_code                   8733938
country_code               7393551
contact_name               9831491
comm_number_qualifier      8172103
comm_number                8173905
dtype: int64

In [11]:
ams_consignee = pd.read_csv("BronzeLayerData/2019/consignee/ams__consignee_2019__202001080000_part_0.csv")

ams_consignee

,identifier,consignee_name,consignee_address_1,consignee_address_2,consignee_address_3,consignee_address_4,city,state_province,zip_code,country_code,contact_name,comm_number_qualifier,comm_number
0,201901010,TOLL GLOBAL FORWARDING (USA) INC.,"1370 VALLEY VISTA DR.,SUITE150",DIAMOND BAR CA,UNITED STATES,NaN,NaN,NaN,NaN,NaN,NaN,Telephone Number,3632400
1,201901011,LADY LORD WEST INC,1441 KWIS AVENUE,NaN,NaN,NaN,HECIENDA HEIGHTS,CA,91745,US,NaN,NaN,NaN
2,201901015,"IKEA INDUSTRY DANVILLE, LLC",100 IKEA DRIVE,RINGGOLD VA 24586 US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201901017,AERO SYSTEMS ENGINEERING INC,358 E FILLMORE AVE,ST PAUL MN 55107 US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,201901018,CHAR-BROIL LLC,1442 BELFAST AVENUE,COLUMBUS GA 31904 US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,201908287390,"RAFAEL J. NIDO, INC.","CARR. #866, KM.1.5",BO. CANDELARIA ARENAS,NaN,NaN,TOA BAJA,PR,00949-,PR,MICHAEL REYES,NaN,NaN
9999996,201908287391,"MUNOZ BAKERY EQUIPMENT, INC.","CARR. #169, KM.5.0",NaN,NaN,NaN,GUAYNABO,PR,00970-,PR,MICHAEL REYES,NaN,NaN
9999997,201908287392,"SMART SUPPLY CHAIN INC,","7324 SOUTHWEST FWY, STE1045,",HOUSTON TX 77074-,NaN,NaN,HOUSTON TX 77074-,TX,77074,US,NaN,NaN,NaN
9999998,201908287393,DFF INC.,1767 JESUS T. PINERO AVENUE URB.,"SUMMIT HILLS SAN JUAN, PR 00920",TEL:787-257-1301 ATTN:MS.LINDA,NaN,NaN,NaN,NaN,NaN,NaN,Telephone Number,RAZICK MRN:0013647-0021
9999999,201908287394,DSV AIR & SEA INC. - I902,"SUITE 405 CLARK 100 WALNUT AVENUE,",CLARK NJ 07066 UNITED STATES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

ams_header {

    identifier int PRIMARY KEY,   (*)
    carrier_code varchar(4),
    estimated_arrival_date DATE(2017-02-14),
    record_status_indicator varchar(15), (Need to Delete the deleted rows, keep the new rows, and adjust the amended)
    place_of_receipt varchar(25),
    conveyance_id_qualifier varchar(25),
    conveyance_id int,
    in_bond_entry_type,
    mode_of_transportation, (0 or 1)
    actual_arrival_date date,
    vessel_id INT
    port_id INT
    shipper_id INT
    consignee_id INT
    FOREIGN KEY (consignee_id) REFERENCES ams_consignee(consignee_id)
    FOREIGN KEY (shipper_id) REFERENCES ams_shipper(shipper_id)
    FOREIGN KEY (port_id) REFERENCES ams_port(port_id)
    FOREIGN KEY (vessel_id) REFERENCES ams_vessel(vessel_id)

}

ams_secondary_notify_party {
    
    identitfier INT PRIMARY KEY,
    notify_party_sequence INT
    notify_party_name VARCHAR(255),
    FOREIGN KEY (identifier) REFERENCES ams_header(identifier)

}

ams_cargo_measurement (

    identifier INT PRIMARY KEY,
    manifest_quantity INT,
    manfifest_unit VARCHAR(3),
    weight INT,
    weight_unit VARCHAR(15), WILL GET RID OF
    FOREIGN KEY (identifier) REFERENCES ams_header(identifier)

)

ams_port (
    
    port_id INT PRIMARY KEY,
    port_of_unlading varchar(25),
    foreign_port_of_lading_qualifier,
    foreign_port_of_lading,
    port_of_destination varchar(25),
    foreign_port_of_destination_qualifier varchar(25),
    foreign_port_of_destionation,
    FOREIGN KEY(identifier) REFERENCES ams_header(identifier)
)

ams_vessel (

    vessel_id INT PRIAMRY KEY,
    vessel_country_code VARCHAR(2),
    vessel_name varchar(25)
)

ams_consignee {
    
    consignee_id int, (*)
    consignee_name varchar(25), (*)
    consignee_address_1 varchar(50),
    consignee_address_2 varchar(50),
    consignee_address_3 varchar(50),

}

ams_shipper{

    shipper_id int PRIMARY KEY,
    shipper_party_name varchar(25), (*)
    shipper_party_address_1 varchar(25),
    shipper_party_address_2 varchar(25),
    shipper_party_address_3 varchar(25)

}

- Drop columns are mostly null in Silver Null. Drop Actual columns in gold layer.
- Break String columns, convert all into kilograms then drop the unit column, splitting city and state and creating two columns from that, creating lookup tables (0, 1), drop nulls rows


Table ams_header {
  identifier integer [primary key]
  carrier_code varchar(4)
  estimated_arrival_date date
  record_status_indicator varchar(1)
  place_of_receipt varchar(25)
  conveyance_id_qualifier varchar(25)
  conveyance_id integer
  in_bond_entry_type varchar
  mode_of_transportation varchar
  actual_arrival_date date
  vessel_id integer
  shipper_id integer
  consignee_id integer
  unlading_port_id integer
  lading_qualifier_id integer
  lading_port_id intger
  destination_port_id integer
  destination_qualifier_id integer
  
}

Table ams_secondary {
  identifier integer [primary key]
  notify_party_sequence intger
  notify_party_name varchar
}

Table ams_cargo_measurement {
  identifier integer [primary key]
  manifest_quantity intger
  manfiest_unit varchar(3)
  weight integer
  measurement integer
  measurement_unit varchar
}

Table ams_port {
  port_id integer [primary key]
  port_name varchar
  
}

Table ams_vessel {
  vessel_id integer [primary key]
  vessel_country_code varchar(2)
  vessel_name varchar(25)
}

Table ams_shipper {
  shipper_id integer [primary key]
  shipper_party_name varchar(25)
  shipper_party_address_1 varchar(25)
  shipper_party_address_2 varchar(25)
  shipper_party_address_3 varchar(25)
}

Table ams_consignee {
  consignee_id integer [primary key]
  consignee_name varchar(25)
  consignee_address_1 varchar(25)
  consignee_address_2 varchar(25)
  consignee_address_3 varchar(25)
}

// ams_header foreign keys
Ref: ams_header.unlading_port_id > ams_port.port_id
Ref: ams_header.lading_qualifier_id > ams_port.port_id
Ref: ams_header.lading_port_id > ams_port.port_id
Ref: ams_header.destination_port_id > ams_port.port_id
Ref: ams_header.destination_qualifier_id > ams_port.port_id
Ref: ams_header.vessel_id > ams_vessel.vessel_id
Ref: ams_header.shipper_id > ams_shipper.shipper_id
Ref: ams_header.consignee_id > ams_consignee.consignee_id

// Child tables tied to ams_header
Ref: ams_secondary.identifier > ams_header.identifier
Ref: ams_cargo_measurement.identifier > ams_header.identifier

Ams_header{
    Lading_port_id
    Destination_port_id

    Lading_port_id references ams_port_id(port_id)
}

ams_port {
Port_id,
Port_name,
port_qualifier
}

---

Table fact_header {
  identifier integer [primary key]
  
  estimated_arrival_date date
  actual_arrival_date date
  vessel_id integer
  shipper_id integer
  consignee_id integer
  unlading_port_id integer
  lading_qualifier_id integer
  lading_port_id intger
  destination_port_id integer
  destination_qualifier_id integer
  manifest_quantity integer
  weight integer
  measurement integer
}


Table dim_cargo_measurement {
  identifier integer [primary key]
  manfiest_unit varchar(3)
  measurement_unit varchar
}

Table dim_port {
  port_id integer [primary key]
  port_name varchar
  
}

Table dim_vessel {
  vessel_id integer [primary key]
  vessel_country_code varchar(2)
  vessel_name varchar(25)
}

Table dim_shipper {
  shipper_id integer [primary key]
  shipper_party_name varchar(25)
  shipper_party_address_1 varchar(25)
  shipper_party_address_2 varchar(25)
  shipper_party_address_3 varchar(25)
}

Table dim_consignee {
  consignee_id integer [primary key]
  consignee_name varchar(25)
  consignee_address_1 varchar(25)
  consignee_address_2 varchar(25)
  consignee_address_3 varchar(25)
}

// ams_header foreign keys
Ref: fact_header.unlading_port_id > dim_port.port_id
Ref: fact_header.lading_qualifier_id > dim_port.port_id
Ref: fact_header.lading_port_id > dim_port.port_id
Ref: fact_header.destination_port_id > dim_port.port_id
Ref: fact_header.destination_qualifier_id > dim_port.port_id
Ref: fact_header.vessel_id > dim_vessel.vessel_id
Ref: fact_header.shipper_id > dim_shipper.shipper_id
Ref: fact_header.consignee_id > dim_consignee.consignee_id

// Child tables tied to ams_header
Ref: dim_cargo_measurement.identifier > fact_header.identifier